import { readFileSync } from "fs";
import { Veritas, QueryContext, Message } from "./pkg/libveritas.js";

// Load fixtures generated by `cargo run --example generate_fixture -p libveritas_testutil`
const anchors = JSON.parse(readFileSync("examples/fixture/anchors.json", "utf8"));
const msgBytes = readFileSync("examples/fixture/message.bin");

// Create verifier (withDevMode for test fixtures)
const veritas = Veritas.withDevMode(anchors);
console.log(`anchors: ${veritas.oldestAnchor()} .. ${veritas.newestAnchor()}`);

// Build query context (empty = verify all handles)
const ctx = new QueryContext();

// Verify message
const msg = new Message(msgBytes);
const result = veritas.verifyMessage(ctx, msg);

// Zones (now proper objects with methods)
const zones = result.zones();
console.log(`\n${zones.length} zones verified:`);
for (const z of zones) {
  console.log(`  ${z.handle()} -> ${z.sovereignty()} (anchor ${z.anchor()})`);
}

// Compare zones
if (zones.length >= 2) {
  const a = zones[0];
  const b = zones[1];
  // These are different handles so isBetterThan will error — just showing the API exists
  try {
    console.log(`\n${a.handle()} better than ${b.handle()}? ${a.isBetterThan(b)}`);
  } catch (e) {
    console.log(`\nisBetterThan(${a.handle()}, ${b.handle()}): ${e.message} (expected — different handles)`);
  }
}

// Zone bytes for storage
const sovereignBytes = zones[0].toBytes();
console.log(`\n@sovereign zone bytes: ${sovereignBytes.length} bytes`);

// Zone as JS object
const sovereignObj = zones[0].toJson();
console.log(`@sovereign zone json keys: ${Object.keys(sovereignObj).join(", ")}`);

// Certificates
const certs = result.certificates();
console.log(`\n${certs.length} certificates:`);
for (const c of certs) {
  console.log(`  ${c.subject} [${c.witness === "Root" || c.witness?.Root ? "root" : "leaf"}]`);
}

console.log("\ndone.");
